export default defineAppConfig({
  profile: {
    name: 'Kirill Shevtsov',
    position: 'Frontend Developer',
    email: 'shev.kv.1982@gmail.com',
    phone: '+380684479024',
    city: 'Kharkiv, Ukraine',
    // photo: '/photo.jpg',
  },
  projects: [
    {
      id: 1,
      name: 'Umlaut Digital',
      description: 'Company website',
      link: 'https://umlaut.digital',
      linkGitHub: 'https://github.com/AeroKir/umlaut-digital',
      image: '/projects/umlaut-digital.png',
      technologies: ['Nuxt 3', 'TailwindCSS', 'Vue 3', 'Pinia', 'Vitest', 'Vite'],
      solvedTasks: [],
      yearsOfDevelopment: '2023 - present',
      tags: ['Vue', 'Nuxt', 'TailwindCSS'],
      screenshots: [
        '/projects/umlaut-digital-1.png',
        '/projects/umlaut-digital-2.png',
        '/projects/umlaut-digital-3.png',
      ],
      notes: 'This project was developed using the latest technologies and best practices.',
    },
    {
      id: 2,
      name: 'Ask4games',
      description: 'Info portal',
      link: 'https://ask4games.com/',
      linkGitHub: 'https://github.com/AeroKir/ask4games',
      image: '/projects/ask4games.png',
      technologies: ['Nuxt 2', 'TailwindCSS', 'Vue 2', 'Pinia', 'Vitest', 'Vite'],
      solvedTasks: [],
      yearsOfDevelopment: '2020 - 2023',
      tags: ['Vue', 'Nuxt', 'TailwindCSS'],
      screenshots: [
        '/projects/ask4games-1.png',
        '/projects/ask4games-2.png',
        '/projects/ask4games-3.png',
      ],
      notes: 'This project was developed using the latest technologies and best practices.',
    },
    {
      id: 3,
      name: 'Dopomoga',
      description: 'Dopomoga website',
      link: 'https://aerokir.github.io/dopomoga/',
      linkGitHub: 'https://github.com/AeroKir/ask4games',
      image: '/projects/ask4games.png',
      technologies: ['Nuxt 2', 'TailwindCSS', 'Vue 2', 'Pinia', 'Vitest', 'Vite'],
      solvedTasks: [],
      yearsOfDevelopment: '2022',
      tags: ['Vue', 'Nuxt', 'TailwindCSS'],
      screenshots: [
        '/projects/ask4games-1.png',
        '/projects/ask4games-2.png',
        '/projects/ask4games-3.png',
      ],
      notes: 'This project was developed using the latest technologies and best practices.',
    },
    {
      id: 4,
      name: 'Gif-app',
      description: 'Gif search application',
      link: 'https://aerokir.github.io/gif-app/#/',
      linkGitHub: 'https://github.com/AeroKir/gif-app',
      image: '/projects/gif-app.png',
      technologies: ['Nuxt 2', 'TailwindCSS', 'Vue 2', 'Pinia', 'Vitest', 'Vite'],
      solvedTasks: [],
      yearsOfDevelopment: '2024',
      tags: ['Vue', 'Nuxt', 'TailwindCSS'],
      screenshots: [
        '/projects/ask4games-1.png',
        '/projects/ask4games-2.png',
        '/projects/ask4games-3.png',
      ],
      notes: 'This project was developed using the latest technologies and best practices.',
    },
    {
      id: 5,
      name: 'Previous portfolio',
      description: 'Previous portfolio website',
      link: 'https://aerokir.github.io/portfolio/',
      linkGitHub: 'https://github.com/AeroKir/ask4games',
      image: '/projects/ask4games.png',
      technologies: ['Nuxt 2', 'TailwindCSS', 'Vue 2', 'Pinia', 'Vitest', 'Vite'],
      solvedTasks: [],
      yearsOfDevelopment: '2019',
      tags: ['Vue', 'Nuxt', 'TailwindCSS'],
      screenshots: [
        '/projects/ask4games-1.png',
        '/projects/ask4games-2.png',
        '/projects/ask4games-3.png',
      ],
      notes: 'This project was developed using the latest technologies and best practices.',
    },
    {
      id: 6,
      name: 'Random user test task',
      description: 'Random user test task description',
      link: 'https://aerokir.github.io/randomuser-test/',
      linkGitHub: 'https://github.com/AeroKir/ask4games',
      image: '/projects/ask4games.png',
      technologies: ['Nuxt 2', 'TailwindCSS', 'Vue 2', 'Pinia', 'Vitest', 'Vite'],
      solvedTasks: [],
      yearsOfDevelopment: '2020',
      tags: ['Vue', 'Nuxt', 'TailwindCSS'],
      screenshots: [
        '/projects/ask4games-1.png',
        '/projects/ask4games-2.png',
        '/projects/ask4games-3.png',
      ],
      notes: 'This project was developed using the latest technologies and best practices.',
    },
    {
      id: 7,
      name: 'Email send app',
      description: 'Email sending application test task',
      link: 'https://aerokir.github.io/sendsay-test-app/',
      linkGitHub: 'https://github.com/AeroKir/ask4games',
      image: '/projects/ask4games.png',
      technologies: ['Nuxt 2', 'TailwindCSS', 'Vue 2', 'Pinia', 'Vitest', 'Vite'],
      solvedTasks: [],
      yearsOfDevelopment: '2020',
      tags: ['Vue', 'Nuxt', 'TailwindCSS'],
      screenshots: [
        '/projects/ask4games-1.png',
        '/projects/ask4games-2.png',
        '/projects/ask4games-3.png',
      ],
      notes: 'This project was developed using the latest technologies and best practices.',
    },
    {
      id: 8,
      name: 'Avia trip app',
      description: 'Avia trip application test task',
      link: 'https://aerokir.github.io/avia-trip-app/',
      linkGitHub: 'https://github.com/AeroKir/ask4games',
      image: '/projects/ask4games.png',
      technologies: ['Nuxt 2', 'TailwindCSS', 'Vue 2', 'Pinia', 'Vitest', 'Vite'],
      solvedTasks: [],
      yearsOfDevelopment: '2019',
      tags: ['Vue', 'Nuxt', 'TailwindCSS'],
      screenshots: [
        '/projects/ask4games-1.png',
        '/projects/ask4games-2.png',
        '/projects/ask4games-3.png',
      ],
      notes: 'This project was developed using the latest technologies and best practices.',
    },
    {
      id: 9,
      name: 'Karpaty Journey',
      description: 'Karpaty Journey OSM Leaflet maps project',
      link: 'https://karpatyjourney.github.io/',
      linkGitHub: 'https://github.com/AeroKir/ask4games',
      image: '/projects/ask4games.png',
      technologies: ['Nuxt 2', 'TailwindCSS', 'Vue 2', 'Pinia', 'Vitest', 'Vite'],
      solvedTasks: [],
      yearsOfDevelopment: '2018',
      tags: ['Vue', 'Nuxt', 'TailwindCSS'],
      screenshots: [
        '/projects/ask4games-1.png',
        '/projects/ask4games-2.png',
        '/projects/ask4games-3.png',
      ],
      notes: 'This project was developed using the latest technologies and best practices.',
    },
    {
      id: 10,
      name: 'First web site',
      description: 'First web site test task',
      link: 'https://aerokir.github.io/lauda.html',
      linkGitHub: 'https://github.com/AeroKir/ask4games',
      image: '/projects/ask4games.png',
      technologies: ['Nuxt 2', 'TailwindCSS', 'Vue 2', 'Pinia', 'Vitest', 'Vite'],
      solvedTasks: [],
      yearsOfDevelopment: '2016',
      tags: ['Vue', 'Nuxt', 'TailwindCSS'],
      screenshots: [
        '/projects/ask4games-1.png',
        '/projects/ask4games-2.png',
        '/projects/ask4games-3.png',
      ],
      notes: 'This project was developed using the latest technologies and best practices.',
    },
  ],
  socials: [
    {
      label: 'Email',
      href: 'mailto:shev.kv.1982@gmail.com',
      icon: 'email',
      display: 'shev.kv.1982@gmail.com',
    },
    {
      label: 'Telegram',
      href: 'https://t.me/Kirill_Shevtsov',
      icon: 'telegram',
      display: 'Telegram',
    },
    {
      label: 'Phone',
      href: 'tel:+380684479024',
      icon: 'phone',
      display: '+380684479024',
    },
    {
      label: 'GitHub',
      href: 'https://github.com/AeroKir',
      icon: 'github',
      display: 'GitHub',
    },
    {
      label: 'LinkedIn',
      href: 'https://www.linkedin.com/in/aerokir-space/',
      icon: 'linkedin',
      display: 'LinkedIn',
    },
  ],
});
