export default defineAppConfig({
  profile: {
    name: 'Kirill Shevtsov',
    position: 'Frontend Developer',
    email: 'shev.kv.1982@gmail.com',
    phone: '+380684479024',
    city: 'Kharkiv, Ukraine',
    // photo: '/photo.jpg',
  },
  projects: [
    {
      id: 1,
      slug: 'umlaut-digital',
      name: 'projects.umlaut.name',
      excerpt: 'projects.umlaut.excerpt',
      description: 'projects.umlaut.description',
      link: 'https://umlaut.digital',
      image: '/projects/umlaut/umlaut-main.jpg',
      imageAlt: 'Umlaut Digital project screenshot',
      previewVideo: '/projects/umlaut/umlaut-video.mp4',
      technologies: ['Nuxt 3', 'Vue 3', 'TypeScript', 'TailwindCSS', 'i18n', 'Strapi', 'VPS', 'Nginx'],
      solvedTasks: ['Implemented a responsive design that adapts seamlessly to various screen sizes and devices.', 'Optimized website performance, resulting in a 30% reduction in load times and improved user experience.', 'Integrated third-party APIs to enhance functionality and provide real-time data updates.', 'Developed reusable components to streamline the development process and ensure consistency across the application.', 'Collaborated with the design team to implement a modern and visually appealing user interface.'],
      yearsOfDevelopment: '2025',
      projectType: 'projects.umlaut.projectType',
      tags: ['Vue', 'Nuxt', 'TailwindCSS'],
      screenshots: [
        '/projects/umlaut/umlaut-main-page.jpg',
        '/projects/umlaut/umlaut-main-page.jpg',
        '/projects/umlaut/umlaut-main-page.jpg',
        '/projects/umlaut/umlaut-main-page.jpg',
        '/projects/umlaut/umlaut-main-page.jpg',
      ],
      notes: 'This project was developed using the latest technologies and best practices.',
    },
    {
      id: 2,
      slug: 'ask4games',
      name: 'projects.ask4games.name',
      excerpt: 'projects.ask4games.excerpt',
      description: 'projects.ask4games.description',
      link: 'https://ask4games.com/',
      image: '/projects/ask/ask-main.jpg',
      imageAlt: 'Ask4games project screenshot',
      technologies: ['Nuxt 2', 'Vue 2', 'Vuex', 'vee-validate', 'JavaScript', 'SCSS', 'i18n'],
      solvedTasks: [],
      yearsOfDevelopment: '2020 - 2023',
      projectType: 'projects.ask4games.projectType',
      tags: ['Vue', 'Nuxt', 'TailwindCSS'],
      screenshots: [
        '/projects/umlaut/umlaut-main-page.jpg',
        '/projects/umlaut/umlaut-main-page.jpg',
        '/projects/umlaut/umlaut-main-page.jpg',
      ],
      notes: 'This project was developed using the latest technologies and best practices.',
    },
    {
      id: 3,
      slug: 'dopomoga',
      name: 'projects.dopomoga.name',
      excerpt: 'projects.dopomoga.excerpt',
      description: 'projects.dopomoga.description',
      link: 'https://aerokir.github.io/dopomoga/',
      linkGitHub: 'https://github.com/AeroKir/ask4games',
      image: '/projects/dopomoga/dopomoga-main.jpg',
      imageAlt: 'Dopomoga project screenshot',
      technologies: ['Nuxt 2', 'TailwindCSS', 'Vue 2', 'Pinia', 'Vitest', 'Vite'],
      solvedTasks: [],
      yearsOfDevelopment: '2022',
      projectType: 'projects.dopomoga.projectType',
      tags: ['Vue', 'Nuxt', 'TailwindCSS'],
      screenshots: [
        '/projects/ask4games-1.png',
        '/projects/ask4games-2.png',
        '/projects/ask4games-3.png',
      ],
      notes: 'This project was developed using the latest technologies and best practices.',
    },
    {
      id: 4,
      slug: 'gif-app',
      name: 'projects.gifApp.name',
      excerpt: 'projects.gifApp.excerpt',
      description: 'projects.gifApp.description',
      link: 'https://aerokir.github.io/gif-app/#/',
      linkGitHub: 'https://github.com/AeroKir/gif-app',
      image: '/projects/gif-app/gif-app.jpg',
      imageAlt: 'Gif-app project screenshot',
      technologies: ['Nuxt 2', 'TailwindCSS', 'Vue 2', 'Pinia', 'Vitest', 'Vite'],
      solvedTasks: [],
      yearsOfDevelopment: '2024',
      projectType: 'projects.gifApp.projectType',
      tags: ['Vue 3', 'Pinia', 'Vuetify', 'Vite', 'PWA', 'GIPHY API'],
      screenshots: [
        '/projects/ask4games-1.png',
        '/projects/ask4games-2.png',
        '/projects/ask4games-3.png',
      ],
      notes: 'This project was developed using the latest technologies and best practices.',
    },
    {
      id: 5,
      slug: 'nextjs-dashboard',
      name: 'projects.dashboardNextJs.name',
      excerpt: 'projects.dashboardNextJs.excerpt',
      description: 'projects.dashboardNextJs.description',
      link: 'https://nextjs-dashboard-eight-plum-73.vercel.app/',
      linkGitHub: 'https://github.com/AeroKir/nextjs-dashboard',
      image: '/projects/nextjs/next-js-dashboard.jpg',
      imageAlt: 'Next.js dashboard project screenshot',
      technologies: ['Next.js', 'TailwindCSS', 'React', 'Pinia', 'Vitest', 'Vite'],
      solvedTasks: [],
      yearsOfDevelopment: '2024',
      projectType: 'projects.dashboardNextJs.projectType',
      tags: ['Next.js', 'TailwindCSS', 'React'],
      screenshots: [
        '/projects/ask4games-1.png',
        '/projects/ask4games-2.png',
        '/projects/ask4games-3.png',
      ],
      notes: 'Email: user@nextmail.com Password: 123456',
    },
    {
      id: 6,
      slug: 'previous-portfolio',
      name: 'projects.prevPortfolio.name',
      excerpt: 'projects.prevPortfolio.excerpt',
      description: 'projects.prevPortfolio.description',
      link: 'https://aerokir.github.io/portfolio/',
      linkGitHub: 'https://github.com/AeroKir/ask4games',
      image: '/projects/first-portfolio/first-portfolio.jpg',
      imageAlt: 'Previous portfolio project screenshot',
      technologies: ['Nuxt 2', 'TailwindCSS', 'Vue 2', 'Pinia', 'Vitest', 'Vite'],
      solvedTasks: [],
      yearsOfDevelopment: '2019',
      projectType: 'projects.prevPortfolio.projectType',
      tags: ['Vue', 'Nuxt', 'TailwindCSS'],
      screenshots: [
        '/projects/ask4games-1.png',
        '/projects/ask4games-2.png',
        '/projects/ask4games-3.png',
      ],
      notes: 'This project was developed using the latest technologies and best practices.',
    },
    {
      id: 7,
      slug: 'randomuser-test-task',
      name: 'Random user test task',
      excerpt: 'Random user test task description',
      description: 'Random user test task description',
      link: 'https://aerokir.github.io/randomuser-test/',
      linkGitHub: 'https://github.com/AeroKir/ask4games',
      image: '/projects/random-user/random-user.jpg',
      imageAlt: 'Random user test task project screenshot',
      technologies: ['Nuxt 2', 'TailwindCSS', 'Vue 2', 'Pinia', 'Vitest', 'Vite'],
      solvedTasks: [],
      yearsOfDevelopment: '2020',
      projectType: 'Website',
      tags: ['Vue', 'Nuxt', 'TailwindCSS'],
      screenshots: [
        '/projects/ask4games-1.png',
        '/projects/ask4games-2.png',
        '/projects/ask4games-3.png',
      ],
      notes: 'This project was developed using the latest technologies and best practices.',
    },
    {
      id: 8,
      slug: 'email-send-form',
      name: 'projects.emailSendForm.name',
      excerpt: 'projects.emailSendForm.excerpt',
      description: 'projects.emailSendForm.description',
      link: 'https://aerokir.github.io/sendsay-test-app/',
      linkGitHub: 'https://github.com/AeroKir/ask4games',
      image: '/projects/email-send-form/email-send-form.jpg',
      imageAlt: 'Email send form project screenshot',
      technologies: ['Nuxt 2', 'TailwindCSS', 'Vue 2', 'Pinia', 'Vitest', 'Vite'],
      solvedTasks: [],
      yearsOfDevelopment: '2020',
      projectType: 'projects.emailSendForm.projectType',
      tags: ['Vue', 'Nuxt', 'TailwindCSS'],
      screenshots: [
        '/projects/ask4games-1.png',
        '/projects/ask4games-2.png',
        '/projects/ask4games-3.png',
      ],
      notes: 'This project was developed using the latest technologies and best practices.',
    },
    {
      id: 9,
      slug: 'avia-tickets-app',
      name: 'projects.aviaTicketsApp.name',
      excerpt: 'projects.aviaTicketsApp.excerpt',
      description: 'projects.aviaTicketsApp.description',
      link: 'https://aerokir.github.io/avia-trip-app/',
      linkGitHub: 'https://github.com/AeroKir/ask4games',
      image: '/projects/avia-trip/avia-trip.jpg',
      imageAlt: 'Avia trip app project screenshot',
      technologies: ['Nuxt 2', 'TailwindCSS', 'Vue 2', 'Pinia', 'Vitest', 'Vite'],
      solvedTasks: [],
      yearsOfDevelopment: '2019',
      projectType: 'projects.aviaTicketsApp.projectType',
      tags: ['Vue', 'Nuxt', 'TailwindCSS'],
      screenshots: [
        '/projects/ask4games-1.png',
        '/projects/ask4games-2.png',
        '/projects/ask4games-3.png',
      ],
      notes: 'This project was developed using the latest technologies and best practices.',
    },
    {
      id: 10,
      slug: 'karpaty-journey',
      name: 'projects.karpatyJourney.name',
      excerpt: 'projects.karpatyJourney.excerpt',
      description: 'projects.karpatyJourney.description',
      link: 'https://karpatyjourney.github.io/',
      linkGitHub: 'https://github.com/AeroKir/ask4games',
      image: '/projects/maps/maps-karpaty-main.jpg',
      imageAlt: 'Karpaty Journey project screenshot',
      technologies: ['Nuxt 2', 'TailwindCSS', 'Vue 2', 'Pinia', 'Vitest', 'Vite'],
      solvedTasks: [],
      yearsOfDevelopment: '2018',
      projectType: 'projects.karpatyJourney.projectType',
      tags: ['Vue', 'Nuxt', 'TailwindCSS'],
      screenshots: [
        '/projects/ask4games-1.png',
        '/projects/ask4games-2.png',
        '/projects/ask4games-3.png',
      ],
      notes: 'This project was developed using the latest technologies and best practices.',
    },
    {
      id: 11,
      slug: 'first-web-site',
      name: 'projects.firstWebSite.name',
      excerpt: 'projects.firstWebSite.excerpt3',
      description: 'First web site test task',
      link: 'https://aerokir.github.io/lauda.html',
      linkGitHub: 'https://github.com/AeroKir/ask4games',
      image: '/projects/first-site/first-site.jpg',
      imageAlt: 'First web site project screenshot',
      technologies: ['HTML', 'CSS', 'GitHub pages'],
      solvedTasks: [],
      yearsOfDevelopment: '2016',
      projectType: 'projects.firstWebSite.projectType',
      tags: ['Vue', 'Nuxt', 'TailwindCSS'],
      screenshots: [
        '/projects/ask4games-1.png',
        '/projects/ask4games-2.png',
        '/projects/ask4games-3.png',
      ],
      notes: 'This project was developed using the latest technologies and best practices.',
    },
  ],
  socials: [
    {
      label: 'Email',
      href: 'mailto:shev.kv.1982@gmail.com',
      icon: 'email',
      display: 'shev.kv.1982@gmail.com',
    },
    {
      label: 'Telegram',
      href: 'https://t.me/Kirill_Shevtsov',
      icon: 'telegram',
      display: 'Telegram',
    },
    {
      label: 'Phone',
      href: 'tel:+380684479024',
      icon: 'phone',
      display: '+380684479024',
    },
    {
      label: 'GitHub',
      href: 'https://github.com/AeroKir',
      icon: 'github',
      display: 'GitHub',
    },
    {
      label: 'LinkedIn',
      href: 'https://www.linkedin.com/in/aerokir-space/',
      icon: 'linkedin',
      display: 'LinkedIn',
    },
  ],
});
